# Generated by Django 5.1.4 on 2025-01-26 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(max_length=100)),
                ('usertype', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='user_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=50)),
                ('Contact', models.CharField(max_length=15)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signapp.user_log')),
            ],
        ),
    ]
