# Generated by Django 5.1.4 on 2025-02-07 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='community_tab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_name', models.CharField(max_length=50)),
                ('community_desc', models.CharField(max_length=350)),
                ('community_logo', models.FileField(upload_to='uploads')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signapp.user_log')),
            ],
        ),
    ]
