# Generated by Django 5.1.4 on 2025-02-12 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signapp', '0003_alter_community_tab_community_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='community_member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_id', to='signapp.user_log')),
                ('community_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signapp.community_tab')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_id', to='signapp.user_log')),
            ],
        ),
    ]
