# Generated by Django 5.1.4 on 2025-02-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signapp', '0005_userchat'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_reg',
            name='img',
            field=models.FileField(default=True, upload_to='uploads/'),
        ),
    ]
