# Generated by Django 5.1.4 on 2025-03-01 08:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signapp', '0006_user_reg_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchat',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userchat',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userchat',
            name='receiver_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signapp.community_tab'),
        ),
        migrations.AlterField(
            model_name='userchat',
            name='sender_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signapp.user_log'),
        ),
    ]
