# Generated by Django 5.1.4 on 2025-03-20 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signapp', '0007_userchat_time_alter_userchat_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='community_member',
            name='user_status',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_reg',
            name='userid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_userid', to='signapp.user_log'),
        ),
    ]
