# Generated by Django 5.1.4 on 2025-03-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signapp', '0008_community_member_user_status_alter_user_reg_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_reg',
            name='meet',
            field=models.CharField(default='', max_length=100),
        ),
    ]
