# Generated by Django 5.1.4 on 2025-03-23 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signapp', '0009_user_reg_meet'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchat',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='signapp.userchat'),
        ),
    ]
