# Generated by Django 5.1.4 on 2025-03-29 18:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signapp', '0010_userchat_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_log',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user_log',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
