# Generated by Django 5.1.4 on 2025-05-03 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signapp', '0013_meet'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_reg',
            name='meeting_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_reg',
            name='receiver_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meeting_receiver', to='signapp.user_log'),
        ),
    ]
